/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors');

export default {
    content: [],
    darkMode: 'class',
    theme: {
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            boxShadow: {
                smooth: '0px 5px 40px rgba(10, 10, 10, 0.1)',
            },
            fontFamily: {
                lato: ['Lato', 'system-ui', 'sans-serif'],
                libre: ['Libre Baskerville', 'system-ui', 'sans-serif'],
            },
            textColor: {
                DEFAULT: '#D0D0D0',
            },
            colors: {
                'muted': colors.gray,
                'success': colors.teal,
                'danger': colors.rose,
                'warning': colors.amber,
                'info': colors.blue,
                'light-gray': {
                    DEFAULT: 'var(--color-light-gray-500)',
                    100: 'var(--color-light-gray-100)',
                    200: 'var(--color-light-gray-200)',
                    300: 'var(--color-light-gray-300)',
                    400: 'var(--color-light-gray-400)',
                    500: 'var(--color-light-gray-500)',
                    900: 'var(--color-light-gray-900)',
                },
                'light-green': {
                    DEFAULT: 'var(--color-light-green-500)',
                    50: 'var(--color-light-green-50)',
                    100: 'var(--color-light-green-100)',
                    150: 'var(--color-light-green-150)',
                    200: 'var(--color-light-green-200)',
                    300: 'var(--color-light-green-300)',
                    400: 'var(--color-light-green-400)',
                    500: 'var(--color-light-green-500)',
                    600: 'var(--color-light-green-600)',
                    700: 'var(--color-light-green-700)',
                    800: 'var(--color-light-green-800)',
                    850: 'var(--color-light-green-850)',
                    900: 'var(--color-light-green-900)',
                    950: 'var(--color-light-green-950)',
                },
                'primary': {
                    DEFAULT: 'var(--color-primary-500)',
                    50: 'var(--color-primary-50)',
                    100: 'var(--color-primary-100)',
                    150: 'var(--color-primary-150)',
                    200: 'var(--color-primary-200)',
                    300: 'var(--color-primary-300)',
                    400: 'var(--color-primary-400)',
                    500: 'var(--color-primary-500)',
                    600: 'var(--color-primary-600)',
                    700: 'var(--color-primary-700)',
                    800: 'var(--color-primary-800)',
                    850: 'var(--color-primary-850)',
                    900: 'var(--color-primary-900)',
                    950: 'var(--color-primary-950)',
                },
                'secondary': {
                    DEFAULT: 'var(--color-secondary-500)',
                    50: 'var(--color-secondary-50)',
                    100: 'var(--color-secondary-100)',
                    150: 'var(--color-secondary-150)',
                    200: 'var(--color-secondary-200)',
                    300: 'var(--color-secondary-300)',
                    400: 'var(--color-secondary-400)',
                    500: 'var(--color-secondary-500)',
                    600: 'var(--color-secondary-600)',
                    700: 'var(--color-secondary-700)',
                    800: 'var(--color-secondary-800)',
                    850: 'var(--color-secondary-850)',
                    900: 'var(--color-secondary-900)',
                    950: 'var(--color-secondary-950)',
                },
                'tertiary': {
                    DEFAULT: 'var(--color-tertiary-500)',
                    50: 'var(--color-tertiary-50)',
                    100: 'var(--color-tertiary-100)',
                    150: 'var(--color-tertiary-150)',
                    200: 'var(--color-tertiary-200)',
                    300: 'var(--color-tertiary-300)',
                    400: 'var(--color-tertiary-400)',
                    500: 'var(--color-tertiary-500)',
                    600: 'var(--color-tertiary-600)',
                    700: 'var(--color-tertiary-700)',
                    800: 'var(--color-tertiary-800)',
                    850: 'var(--color-tertiary-850)',
                    900: 'var(--color-tertiary-900)',
                    950: 'var(--color-tertiary-950)',
                },
                'fourthly': {
                    DEFAULT: 'var(--color-fourthly-500)',
                    50: 'var(--color-fourthly-50)',
                    100: 'var(--color-fourthly-100)',
                    150: 'var(--color-fourthly-150)',
                    200: 'var(--color-fourthly-200)',
                    300: 'var(--color-fourthly-300)',
                    400: 'var(--color-fourthly-400)',
                    500: 'var(--color-fourthly-500)',
                    600: 'var(--color-fourthly-600)',
                    700: 'var(--color-fourthly-700)',
                    800: 'var(--color-fourthly-800)',
                    850: 'var(--color-fourthly-850)',
                    900: 'var(--color-fourthly-900)',
                    950: 'var(--color-fourthly-950)',
                },
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
        require('tailwindcss-animate'),
    ],
};
